# Generated by Django 3.1.1 on 2020-09-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200922_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perpayuser',
            old_name='Company',
            new_name='company',
        ),
    ]
