# Generated by Django 3.1.1 on 2020-09-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200924_2231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perpayuser',
            managers=[
            ],
        ),
    ]
